DEFAULT: &DEFAULT
  black_list: [1,2,3]
  num_gpus_total: 4
  num_gpus_to_use: 1
  heads: 8
  edge_sampling_ratio: 0.9
  seed: 0
  verbose: 2
  save_model: False
  save_plot: False
  val_interval: 1

GAT: &GAT
  model_name: GAT
  <<: *DEFAULT

GAT-Cora: &GAT-Cora
  <<: *GAT
  black_list: [0,1,2]
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-Cora-E: &GAT-Cora-E
  <<: *GAT-Cora
  epochs: 500
  is_super_gat: True


GAT-Cora-EV13: &GAT-Cora-EV13
  <<: *GAT-Cora-E
  attention_type: "prob_mask_only"

GAT-Cora-EV13NSO8: &GAT-Cora-EV13NSO8
  <<: *GAT-Cora-EV13
  out_heads: 8
  edge_sampling_ratio: 0.8
  neg_sample_ratio: 0.5
  l2_lambda: 0.008228864972965771
  att_lambda: 11.346574532931719
  epochs: 600
  dim: 256
  dim_x: 2
  w_loss1: 2.0
  w_loss2: 0.001
  margin1: 0.8
  margin2: 0.2
  NN: 10
  num1: 100
  wd: 0.01
  dropout: 0.2

GAT-CiteSeer: &GAT-CiteSeer
  <<: *GAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-CiteSeer-E: &GAT-CiteSeer-E
  <<: *GAT-CiteSeer
  epochs: 400
  is_super_gat: True

GAT-CiteSeer-EV13: &GAT-CiteSeer-EV13
  <<: *GAT-CiteSeer-E
  attention_type: "prob_mask_only"

GAT-CiteSeer-EV13NSO8: &GAT-CiteSeer-EV13NSO8
  <<: *GAT-CiteSeer-EV13
  out_heads: 8
  edge_sampling_ratio: 0.8
  neg_sample_ratio: 0.5
  l2_lambda:  0.04161321832213915
  att_lambda: 0.013081692727373775
  epochs: 600
  dim: 256
  dim_x: 2
  w_loss1: 2.0
  w_loss2: 2.0
  margin1: 0.7
  margin2: 0.4
  NewATop: 10
  NN: 10
  num1: 100
  wd: 0.01
  dropout: 0.2

GAT-PubMed: &GAT-PubMed
  <<: *GAT
  black_list: [0, 2,3]
  lr: 0.01
  out_heads: 8
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-PubMed-NE: &GAT-PubMed-NE
  <<: *GAT-PubMed
  epochs: 300
  is_super_gat: False

GAT-PubMed-NE-500: &GAT-PubMed-NE-500
  <<: *GAT-PubMed-NE
  l2_lambda: 0.0005
  epochs: 1000
  w_loss1: 2.0
  w_loss2: 10.0
  margin1: 0.4
  margin2: 0.1
  NewATop: 5
  dim: 128
  dim_x: 4
  NN: 5
  num1: 100
  wd: 0.01
  dropout: 0.2

GAT-WikiCS: &GAT-WikiCS
  <<: *GAT
  black_list: [0,1,2]
  lr: 0.01
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8
  epochs: 500
  to_undirected_at_neg: True


GAT-WikiCS-NE:  &GAT-WikiCS-NE
  <<: *GAT-WikiCS
  is_super_gat: False
  epochs: 5000
  w_loss1: 2000
  w_loss2: 20
  margin1: 0.9
  margin2: 0.1
  dim: 512
  dim_x: 1
  NewATop: 0
  dropout: 0.1
  NN: 5
  num1: 300
  wd: 0.0

GAT-Photo: &GAT-Photo
  <<: *GAT
  black_list: [0, 3,1]
  lr: 0.01
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8
  epochs: 500
  to_undirected_at_neg: True


GAT-Photo-E: &GAT-Photo-E
  <<: *GAT-Photo
  is_super_gat: True
  epochs: 5000
  w_loss1: 200
  w_loss2: 2
  margin1: 0.9
  margin2: 0.2
  dim: 128
  dim_x: 4
  NewATop: 0
  dropout: 0.1
  NN: 5
  num1: 200
  wd: 0.0

GAT-Crocodile: &GAT-Crocodile
  <<: *GAT
  black_list: [2,0,3]
  lr: 0.01
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8
  epochs: 200
  to_undirected_at_neg: True

GAT-Crocodile-E: &GAT-Crocodile-E
  <<: *GAT-Crocodile
  is_super_gat: True
  epochs: 2000
  w_loss1: 200
  w_loss2: 2
  margin1: 0.9
  margin2: 0.2
  dim: 256
  dim_x: 2
  NewATop: 0
  dropout: 0.1
  NN: 5
  num1: 200
  wd: 0.0

GAT-CoraFull: &GAT-CoraFull
  <<: *GAT
  black_list: [0,1,2]
  lr: 0.01
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8
  epochs: 500
  to_undirected_at_neg: True

GAT-CoraFull-E: &GAT-CoraFull-E
  <<: *GAT-CoraFull
  epochs: 500
  is_super_gat: True

GAT-CoraFull-EV13: &GAT-CoraFull-EV13
  <<: *GAT-CoraFull-E
  attention_type: "prob_mask_only"
  epochs: 3900
  w_loss1: 400
  w_loss2: 4
  margin1: 0.9
  margin2: 0.6
  dim: 256
  dim_x: 4
  NewATop: 0
  dropout: 0.1
  NN: 5
  num1: 200
  wd: 0.0

GAT-DBLP: &GAT-DBLP
  <<: *GAT
  black_list: [1,2,3]
  lr: 0.01
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8
  epochs: 200
  to_undirected_at_neg: True

GAT-DBLP-E: &GAT-DBLP-E
  <<: *GAT-DBLP
  is_super_gat: True
  epochs: 400
  w_loss1: 20
  w_loss2: 20
  margin1: 0.7
  margin2: 0.1
  dim: 512
  dim_x: 1
  NewATop: 0
  dropout: 0.1
  NN: 5
  num1: 200
  wd: 0.0
